---
title: ''
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=F, message=F, warning=F}

library(tidyverse)
library(echarts4r)
library(htmltools)
setwd("..")
source("R/global_utils.R")

graph <- data.frame(x=seq(1,4),
                 y=seq(1,4)*8) %>%
  e_charts(x) %>%
  e_line(y)

graph2 <- data.frame(x=seq(1,4),
                 y=seq(1,4)*8) %>%
  e_charts(x) %>%
  e_bar(y)


tags$html(
  tags$button(id="myBtn","Open Modal"),
  tags$div(id="myModal",class="modal",
           tags$div(class="modal-content",
                    tags$span(class="close",
                              "X"),
                    tags$div(id="wow",
                             style="height:100%;",
                             buttonFUN(list(graph,graph2),
                                       c("ok","yy"))))
                    )
           )

tags$html(tags$script('// Get the modal
var modal = document.getElementById("myModal");

// Get the button that opens the modal
var btn = document.getElementById("myBtn");

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks the button, open the modal 
btn.onclick = function() {
  modal.style.display = "block";
  window.dispatchEvent(new Event("resize")); 
}
// AMAZING FIX https://stackoverflow.com/questions/1818474/how-to-trigger-the-window-resize-event-in-javascript

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
  modal.style.display = "none";
}

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
  if (event.target == modal) {
    modal.style.display = "none";
  }
}'))

```

<br>
<br>

<!-- ```{r echo=F} -->

<!-- buttonFUN(list(graph,graph2), -->
<!--           c("ok","yy")) -->

<!-- ``` -->

```{=html}

<style>

.html-widget {
  
}

/* The Modal (background) */
.modal {
  display: none; /* Hidden by default */
  position: fixed; /* Stay in place */
  z-index: 1; /* Sit on top */
  padding-top: 100px; /* Location of the box */
  left: 0;
  top: 0;
  width: 100%; /* Full width */
  height: 100%; /* Full height */
  overflow: auto; /* Enable scroll if needed */
  background-color: rgb(0,0,0); /* Fallback color */
  background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
}

/* Modal Content */
.modal-content {
  background-color: #fefefe;
  margin: auto;
  padding: 20px;
  border: 1px solid #888;
  width: 80%;
}

/* The Close Button */
.close {
  color: #aaaaaa;
  float: right;
  font-size: 28px;
  font-weight: bold;
}

.close:hover,
.close:focus {
  color: #000;
  text-decoration: none;
  cursor: pointer;
}

</style>

<script>

</script>


```



























